apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-mgmt
  template:
    metadata:
      labels:
        app: stock-mgmt
    spec:
      containers:
        - name: stock-mgmt
          image: ghcr.io/recepbaykara/stock-mgmt:sha-4de088123a5f937d8cc4fdfe285d798066de928c
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              value: Host=postgres;Port=5432;Database=stockdb;Username=stockuser;Password=stockpass
            - name: JAEGER_HOST
              value: jaeger.monitoring
            - name: JAEGER_PORT
              value: "6831"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.monitoring:4317
---

apiVersion: v1
kind: Service
metadata:
  name: stock-mgmt
spec:
  type: LoadBalancer
  selector:
    app: stock-mgmt
  ports:
    - port: 80
      targetPort: 8080
