apiVersion: batch/v1
kind: Job
metadata:
  name: stock-mgmt-migration
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/recepbaykara/stock-mgmt:sha-4de088123a5f937d8cc4fdfe285d798066de928c
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Running EF migration bundle..."
              /app/efbundle --verbose
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              value: Host=postgres;Port=5432;Database=stockdb;Username=stockuser;Password=stockpass

